# 1.server
server:
  port: 8084


# 2.log
logging:
  level:
    org.springframework.cloud.gateway: info
# 3. openfeign
feign:
  circuitbreaker:
    enabled: true
# 4. 为了监控网关
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  eureka:
    instance:
      hostname: cloud-gateway-service
    client: # 服务提供者provider注册金eureka服务列表内
      service-url:
        register-with-eureka: true
        fetch-registry: true
      defaultZone: http://localhost:8761/eureka/
# 5.spring
spring:
  application:
    name: zuul
  # 统一设置返回的时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_NULL
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-provider #payment_routh    #路由的ID，没有固定规则但要求唯一，简易配合服务名
          uri: lb://service-provider         #匹配后提供服务的路由地址
          predicates:
            - Path=/provider/**   #断言，路径相匹配的进行路由
#          filters:
#            - StripPrefix=1



