eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8801/eureka/
  instance:
    prefer-ip-address: true
    # Eureka客户端向服务心跳的时间间隔是1s，默认是30秒
    lease-renewal-interval-in-seconds: 1
    # Eureka服务端在收到一次心跳后等待时间上限是2s，默认是90s，超时将剔除该微服务，其实Eureka服务端已经设置了，可能就是也告诉服务提供者一下
    lease-expiration-duration-in-seconds: 2
server:
  port: 8762
  servlet:
    context-path: "/provider"
spring:
  application:
    name: service-provider
  datasource:
    url: jdbc:mysql://localhost:3306/zhuhanmei?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false&useUnicode=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
# mybatis-plus 配置
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  #config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.example.serverprovider.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    # 热加载mapper文件
    refresh: true
    db-config:
      db-type: mysql
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.authorize: DEBUG


